apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-admin
  namespace: default  
subjects:
- kind: User
  name: 4eef7bb2-1ab5-4eab-9dbc-f2c3a010a8b5
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: full-access-role
  apiGroup: rbac.authorization.k8s.io
